default_retention = 5

[droplets]
  [[droplets.by_name]]
  name = "server01"
  retention = 3

  [[droplets.by_name]]
  name = "server02"

  [[droplets.by_tag]]
  tag = "prod"
  retention = 20

[volumes]
  [[volumes.by_name]]
  name = "db01"

  [[volumes.by_tag]]
  name = "redis"
